// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu8O_PW3UNN1--5et3BaCqhZ4_B1wGbvA',
    appId: '1:678900420337:android:6bd63c711039100af0e350',
    messagingSenderId: '678900420337',
    projectId: 'app-urgencias-oftamologicas',
    databaseURL: 'https://app-urgencias-oftamologicas-default-rtdb.firebaseio.com',
    storageBucket: 'app-urgencias-oftamologicas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy9DzG7lK_aGJOuQJ8iUSiVCFYnHg9QGU',
    appId: '1:678900420337:ios:1ffe865382b22a87f0e350',
    messagingSenderId: '678900420337',
    projectId: 'app-urgencias-oftamologicas',
    databaseURL: 'https://app-urgencias-oftamologicas-default-rtdb.firebaseio.com',
    storageBucket: 'app-urgencias-oftamologicas.appspot.com',
    androidClientId: '678900420337-ue0l1o7aahqr076stc3at8jfp6d6fet7.apps.googleusercontent.com',
    iosClientId: '678900420337-as2alp9kq2jisjjs286ud3p5m7pvneic.apps.googleusercontent.com',
    iosBundleId: 'com.example.urgenciasOftamologicas',
  );
}
